services:
  backend:
    build:
      context: ./taskManagerBackend
      dockerfile: Dockerfile
    container_name: taskmanager-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PORT=5000
      - SUPABASE_URL=https://qowzmhcydxxfbtrzangl.supabase.co
      - SUPABASE_KEY=sb_publishable_mOc3dW_eS63LUursi357Jw_rBsKOGaX
      - DATABASE_URL=postgresql://postgres.qowzmhcydxxfbtrzangl:qWM6PqxgW%3FyMEW%40@aws-0-ap-south-1.pooler.supabase.com:6543/postgres
      - FRONTEND_URL=http://localhost:3000
      - GMAIL_USER=${GMAIL_USER:-}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD:-}
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
    restart: unless-stopped

  frontend:
    build:
      context: ./taskmanager-frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=https://qowzmhcydxxfbtrzangl.supabase.co
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=sb_publishable_mOc3dW_eS63LUursi357Jw_rBsKOGaX
        - NEXT_PUBLIC_API_URL=http://localhost:5000
    container_name: taskmanager-frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - backend
    restart: unless-stopped
